import { Container } from "@/components/layouts";
import { BannerCard } from "@/components/molecules";
import { Banner, DiscoverSection, ExploreNearbySection, Footer, Header } from "@/components/organisms";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Discover, Explore } from "typings";

interface Props {
  explores: [Explore];
  discovers: [Discover];
}

const Home: NextPage<Props> = ({ explores, discovers }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Banner */}
      <Banner />

      {/* Main */}
      <main>
        <Container className="space-y-16">
          <ExploreNearbySection explores={explores} />
          <DiscoverSection discovers={discovers} />
          <BannerCard />
        </Container>
      </main>

      {/* Footer */}
      <div className="mt-16">
        <Footer />
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const resExplores = await fetch("https://links.papareact.com/pyp");
  const explores = await resExplores.json();

  const resDiscovers = await fetch("https://links.papareact.com/zp1");
  const discovers = await resDiscovers.json();

  return {
    props: {
      explores,
      discovers,
    },
  };
};
